USE practice2_1;

DROP TABLE demo;
CREATE TABLE demo (
	id INT AUTO_INCREMENT PRIMARY KEY,
    email VARCHAR(255) NOT NULL
);

CREATE INDEX email_index ON demo (email);

SELECT * FROM INFORMATION_SCHEMA.STATISTICS 
WHERE TABLE_SCHEMA='practice2_1' AND TABLE_NAME='demo';
